#!/usr/bin/env python

from distutils.core import setup, Extension

fib_module = Extension(
   '_Srt',
   sources=['srt_wrap.c'], # srt_wrap.c is going to be generated by swig
)

setup (
	name        = 'Srt',
	version     = '0.1',
	author      = "Dazzl",
	description = "python binding from the libsrt library from Haivision",
	ext_modules = [srt_module],
	py_modules  = ["Srt"], # name of module that we're going import
)